### ISSUE TITLE
Error with lemondcsv.py

### ISSUE THREAD

**Issue by SOKRider** [tpodowd/lemondcsv#3]
Hi there,

I found this script and was really excited to be able to load my lemond ride data into Strava etc so thanks for creating it.  I'm not sure if it is being supported, but hope so.

I ran the script and received the following error (full list of commends):

tephens-MacBook-Pro:lemond Stephen$ ./lemondcsv.py 08022015.CSV
Traceback (most recent call last):
  File "./lemondcsv.py", line 376, in <module>
    revo = Revolution(iname)
  File "./lemondcsv.py", line 149, in __init__
    self.readCSV(file)
  File "./lemondcsv.py", line 158, in readCSV
    p = Point(row)
  File "./lemondcsv.py", line 75, in __init__
    self.cadence = int(csvrow[5])
ValueError: invalid literal for int() with base 10: '\xbc79'

I am running Mac OS X Yosemite (10.10.4) and Lemond firmware is 63.

I'd really appreciate it if you could help.

I'm happy to send the Lemond csv file ... just not sure how.

Cheers

Stephen

**Comment by tpodowd** [comment]
Hi Stephen. Oh. I haven't used this script in a long time. I still have my lemond but I'm actually using an ANT+ usb stick in combination with TrainerRoad. TrainerRoad then uses speed/cadence to generate virtual power (they have a power graph for the lemond) and you get all your data on screen in trainerroad. TrainerRoad can then automatically upload to strava.

I know that doesn't help you with your current problem. Can you email the problematic file to me and I can have a quick look at it.

Email me at my github username ATgmail.com

**Comment by tpodowd** [comment]
Stephen - thanks for the file. I got it. It's unfortunately corrupt which is why the script has trouble reading it. Here's an example:

    0:37:09,030.2,018.6,0151,131,099,0405,00062,0,^M
    0:37:10,030.1,018.7,0112,130,096,0405,00046,0,^M
    0:37:11,000.0,102.4,0000,012,¼79,9253,10795,0,^M
    0:37:12,000.0,000.0,0000,000,000,0000,00000,0,^M
    0:37:13,000.0,000.0,0000,000,000,0000,00000,0,^M

The first column is time into your workout. So basically all normal up until 0:37:10. Then at 0:37:11, the cadence column has the value '¼79'. Other values on that line are also weird and the brokenness continues until about '0:40:35'. 

My recommendation is to open the file with a file editor such and then throw away your workout after the 0:37:10 line by deleting to the end of the file. That should at least give you a 37min workout.

I've seen this corruption before when the battery is low in the head unit. Perhaps try to replace the battery and hopefully you'll get some non-corrupt workouts going forward that you can convert for strava.

Let me know if that helps. The only thing I could really perhaps change in the script to handle this is to throw away the rest of the file when I detect corruption so at least folks would get something.

**Comment by SOKRider** [comment]
Hi Tom,

Thanks so much!!!  This is great.  I did have a look at the file earlier but as the issue is where it is I didn’t see it.

I edited out after the issue and it loads fine.  I’ll refresh the batteries in the head unit and hopefully it will fix future files.

I don’t think you need to change the script (very nice of you to think of that) now that the issue is clear.

Thanks again.

Cheers

Stephen

**Comment by tpodowd** [comment]
Closing this issue.
