### ISSUE TITLE
Add GPS data?

### ISSUE THREAD

**Issue by timyjen** [tpodowd/lemondcsv#4]
Hi, your script is probably the closest thing I've seen to achieve what I want to do so I'm wondering if you can help me. 

Does your script add GPS data as well in the .tcx file? If not, is it possible to write a version that does?

I uses strava that records gps and exports in .gpx (that I can convert to .tcx), and I have Sigma ROX 9.1 that records all the other stuff (hr, cadence, speed....etc) in .csv. I'm wondering if I can merge the gps info from .gpx and have everything in the converted .tcx?

**Comment by tpodowd** [comment]
Hi @timyjen,

You could certainly use a modified version of the script to read from two files and merge the data points into one. You'd need a distinct sync point where the two data files are considered as starting from and both files would need to agree on how often they log data. So that the data points can be merged correctly. Usually the lemond only logs once per second for example. Another feed could log every 10ms or every 1/2second etc.

This script though is really designed to take a lemond csv file which does not have any GPS coordinates (as it is a dumb trainer) and doesn't have any simulator built in that would generate those points.

Feel free to fork the project and try out your own changes to achieve your desired result. Currently, I can't invest time to help you directly to achieve what you want. I'm closing this issue as it is out of scope wrt the goals of this particular software as is. Best of luck with the code!
